name: Format and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install black
          sudo apt-get update
          sudo apt-get install -y shfmt

      - name: Format Python files
        run: |
          black .
          echo "### Python files formatted with Black:" >> $GITHUB_STEP_SUMMARY
          git status --porcelain '*.py' | awk '{print "- " $2}' >> $GITHUB_STEP_SUMMARY

      - name: Format YAML, CSS, and Markdown files with Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: '--write **/*.{yml,yaml,css,md}'
      
      - name: Summarize YAML, CSS, and Markdown changes
        run: |
          echo "### YAML/YML, CSS, and Markdown files formatted with Prettier:" >> $GITHUB_STEP_SUMMARY
          git status --porcelain '*.yml' '*.yaml' '*.css' '*.md' | awk '{print "- " $2}' >> $GITHUB_STEP_SUMMARY

      - name: Format Shell scripts
        run: |
          shfmt -w -i 2 -sr . || true
          echo "### Shell scripts formatted with shfmt:" >> $GITHUB_STEP_SUMMARY
          git status --porcelain '*.sh' | awk '{print "- " $2}' >> $GITHUB_STEP_SUMMARY

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: auto-format files (yaml, sh, py, css, md)'
